Repository gsistelos/webserv, pull requests merged in 2023-09, with the labels that each got.

#57 27 html pages not loading css files
  assets/images/bg.jpeg
  pages/home/index.html
  pages/home/style.css
  pages/upload/index.html
  pages/upload/style.css
  srcs/Cgi.cpp
  srcs/Client.cpp
Labels: bug

#56 fix: iterate pollfds properly and not coppying parser strings
  includes/Parser.hpp
  srcs/Client.cpp
  srcs/Config.cpp
  srcs/Parser.cpp
  srcs/WebServ.cpp
  webserv.conf
Labels: fix

#62 52 server redirection
  Makefile
  cgi-bin/get.py
  cgi-bin/upload.py
  includes/Cgi.hpp
  includes/Client.hpp
  root/.DS_Store
  root/assets/images/bg.jpeg
  root/home/index.html
  root/home/style.css
  root/index.html
  root/style.css
  root/upload/index.html
  root/upload/style.css
  srcs/Cgi.cpp
  srcs/Client.cpp
  webserv.conf
Labels: enhancement

#67 feat: redirect / to /pages/
  root/pages/index.html
  root/pages/search/index.html
  root/pages/search/style.css
  root/pages/style.css
  root/pages/upload/index.html
  root/pages/upload/style.css
  srcs/Client.cpp
Labels: enhancement

#76 66 create location to config file
  Makefile
  default_pages/403.html
  default_pages/411.html
  includes/Cgi.hpp
  includes/Client.hpp
  includes/Config.hpp
  includes/HttpResponse.hpp
  includes/Server.hpp
  root/no-index/script.js
  root/no-index/style.css
  srcs/Cgi.cpp
  srcs/Client.cpp
  srcs/Config.cpp
  srcs/HttpResponse.cpp
  srcs/Server.cpp
  webserv.conf
Labels: enhancement

#78 75 fix non blocking for cgi
  .gitignore
  Makefile
  includes/Cgi.hpp
  includes/Client.hpp
  includes/Fd.hpp
  includes/Server.hpp
  includes/Socket.hpp
  includes/WebServ.hpp
  srcs/Cgi.cpp
  srcs/Client.cpp
  srcs/Fd.cpp
  srcs/Server.cpp
  srcs/Socket.cpp
  srcs/WebServ.cpp
Labels: enhancement
