Repository gsistelos/webserv, pull requests merged in 2023-08, with the labels that each got.

#5 1 respond request with a page
  Makefile
  includes/Response.hpp
  includes/Server.hpp
  pages/index.html
  srcs/Response.cpp
  srcs/Server.cpp
Labels: enhancement

#19 13 create client class
  Makefile
  includes/Client.hpp
  includes/Request.hpp
  includes/Server.hpp
  includes/Socket.hpp
  includes/WebServ.hpp
  srcs/Client.cpp
  srcs/Request.cpp
  srcs/Server.cpp
  srcs/Socket.cpp
  srcs/WebServ.cpp
Labels: enhancement, fix

#29 22 create form and send post request to cgi
  pages/.DS_Store
  pages/home/index.html
  pages/home/style.css
  pages/index.html
  pages/upload/index.html
  pages/upload/style.css
  srcs/Client.cpp
Labels: enhancement

#32 refactor: remove http cookie from env
  srcs/Client.cpp
Labels: refactor

#33 fix: change startSize to pollfds.size() in for loop
  includes/WebServ.hpp
  srcs/WebServ.cpp
Labels: bug

#37 34 improve cgi env creation
  Makefile
  includes/Cgi.hpp
  srcs/Cgi.cpp
  srcs/Client.cpp
Labels: refactor

#39 fix: added includes for linux
  srcs/Cgi.cpp
Labels: fix

#40 feat: parsing file like nginx and setting server configurations
  Makefile
  includes/Client.hpp
  includes/Parser.hpp
  includes/Server.hpp
  includes/WebServ.hpp
  srcs/Client.cpp
  srcs/Parser.cpp
  srcs/Server.cpp
  srcs/WebServ.cpp
  webserv.conf
Labels: enhancement

#45 feat: handle cgi response to the client
  cgi-bin/upload.py
  includes/Cgi.hpp
  srcs/Cgi.cpp
  srcs/Client.cpp
Labels: enhancement

#47 36 cgi upload fail sometimes
  cgi-bin/upload.py
  includes/Cgi.hpp
  srcs/Cgi.cpp
  srcs/Client.cpp
Labels: enhancement

#50 fix: "bind: address already in use" error
  srcs/Server.cpp
Labels: fix
